version: '3.9'
services:
  ruuter:
    container_name: ruuter
    build:
      context: .
    volumes:
      - ./DSL:/DSL
      - ./constants.ini:/app/constants.ini
    ports:
      - 8080:8080
    networks:
      - bykstack

networks:
  bykstack:
    name: bykstack
    driver: bridge