application:
  config-path: ${user.dir}/DSL
  stopInCaseOfException: true
  logging:
    displayRequestContent: false
    displayResponseContent: false
    printStackTrace: false
    meaningfulErrors: false
  incomingRequests:
    allowedMethodTypes: [ POST, GET ]
    headers:
      header: value

  responseDefaultHeaders:
    Cache-Control: no-cache, no-store, must-revalidate
    Pragma: no-cache
    Expires: 0

  httpCodesAllowList: [ 200, 201, 202 ]
  defaultDslInCaseOfException:
    dsl: default-dsl
    requestType: "POST"
    body:
      someVal: "Hello World"
    query:
      anotherVal: 123
  finalResponse:
      dslWithResponseHttpStatusCode: 200
      dslWithoutResponseHttpStatusCode: 300
  maxStepRecursions: 10
  CORS:
    allowedOrigins: ["https://test.buerokratt.ee", "https://admin.test.buerokratt.ee/", "https://tim.test.buerokratt.ee/"]
    allowCredentials: true
  DSL:
    allowedFiletypes: [".yml", ".yaml", ".tmp", ".DS_Store"]
    processedFiletypes: [".yml", ".yaml"]
    allowDslReloading: true
  internalRequests:
#    disabled: true
    allowedIPs: ["193.40.13.13"]
    allowedURLs: ["http://localhost/internalTest"]
#  openSearchConfiguration:
#    url: http://host.docker.internal:9200
#    index: ruuterlog
  httpResponseSizeLimit: 256

  apiRequestTestingKey: voorshpellhappilo

management:
  endpoints:
    web:
      exposure:
        include=prometheus:
  tracing:
    enabled:
      true

spring:
  application:
    name: ruuter

logging:
  level:
    root: INFO

server:
  error:
    include-stacktrace: never
